[package]
name = "webworm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.8.0"
ron = "0.8.0"
serde = "1.0.160"
webpage = "1.5.0"
cli-clipboard = "0.4"
