[package]
name = "base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
log = "0.4"
webpage = "1"
ron = "0.8"
glob = "0.3"
anyhow = "*"
